# run locally (for dev)
run-local:
	echo "Running locally"
	docker compose --env-file .env.local up -d

# run
run:
	echo "Running"
	docker compose --env-file .env up

# stop
stop:
	echo "Stopping"
	docker compose down
